## Content based Recommended system
there are 3 types of Recommendation  system
1) Content based
2) Collabrative based 
3) Hybrid Based

In [274]:
import pandas as pd
import numpy as np

In [275]:
Movies = pd.read_csv("tmdb_5000_movies.csv")
Credits = pd.read_csv("tmdb_5000_credits.csv")

In [276]:
Movies.head()
Credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

## Merge both Movies Based on title or Id

In [277]:
MoviewdataFrame = Movies.merge(Credits, on="title")

In [278]:
MoviewdataFrame.shape
MoviewdataFrame.info()

<class 'pandas.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4809 non-null   int64
 1   genres                4809 non-null   str
 2   homepage              1713 non-null   str
 3   id                    4809 non-null   int64
 4   keywords              4809 non-null   str
 5   original_language     4809 non-null   str
 6   original_title        4809 non-null   str
 7   overview              4806 non-null   str
 8   popularity            4809 non-null   float64
 9   production_companies  4809 non-null   str
 10  production_countries  4809 non-null   str
 11  release_date          4808 non-null   str
 12  revenue               4809 non-null   int64
 13  runtime               4807 non-null   float64
 14  spoken_languages      4809 non-null   str
 15  status                4809 non-null   str
 16  tagline               3965 non-null   str
 17  title                 4809 non-null   str
 18  vote_average          4809 non-null   float64
 19  vote_count            4809 non-null   int64
 20  movie_id              4809 non-null   int64
 21  cast                  4809 non-null   str
 22  crew                  4809 non-null   str
dtypes: float64(3), int64(5), str(15)
memory usage: 864.2 KB

## Need to work only those colms that will help to recomend the Content 
1) Id
2) genres
3) cast
4) Crew
5) keywords 
6) title
7) overview

In [279]:
contentdataFrame = MoviewdataFrame[
    ["id", "genres", "crew", "cast", "title", "keywords", "overview"]
]
contentdataFrame.head()

,id,genres,crew,cast,title,keywords,overview
0,19995,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...",Avatar,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","In the 22nd century, a paraplegic Marine is di..."
1,285,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...",Pirates of the Caribbean: At World's End,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","Captain Barbossa, long believed to be dead, ha..."
2,206647,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...",Spectre,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",A cryptic message from Bond’s past sends him o...
3,49026,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...",The Dark Knight Rises,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",Following the death of District Attorney Harve...
4,49529,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...",John Carter,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","John Carter is a war-weary, former military ca..."

## check how much data is misssing

In [280]:
contentdataFrame.isnull().sum()

id          0
genres      0
crew        0
cast        0
title       0
keywords    0
overview    3
dtype: int64

## as Overview has 3 Null values so drop it

In [281]:
contentdataFrame = contentdataFrame.dropna()
contentdataFrame.isnull().sum()

id          0
genres      0
crew        0
cast        0
title       0
keywords    0
overview    0
dtype: int64

## check for duplicated Data
Never assing a value to duplicated values other wise not error but bug will acccur

In [282]:
contentdataFrame.duplicated().sum()

np.int64(0)

## Format the data
'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'
this is the data that we are getting 
now the problem is this is in string we need to convert it into list

## For Converting from string to list import the libabry

In [283]:
import ast

ast.literal_eval(
    '[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'
)
# this will convert he data in to this type
# import ast

# ast.literal_eval(
#     '[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'
# )

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 878, 'name': 'Science Fiction'}]

In [284]:
def convert(objct):

    L = []
    for i in ast.literal_eval(objct):
        L.append(i["name"])
        return L

In [285]:
def convert3(objct):

    L = []
    counter = 0
    for i in ast.literal_eval(objct):
        if counter != 0:
            3
        L.append(i["name"])
        counter += 1
        return L

In [286]:
contentdataFrame.head()

,id,genres,crew,cast,title,keywords,overview
0,19995,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...",Avatar,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","In the 22nd century, a paraplegic Marine is di..."
1,285,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...",Pirates of the Caribbean: At World's End,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","Captain Barbossa, long believed to be dead, ha..."
2,206647,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...",Spectre,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",A cryptic message from Bond’s past sends him o...
3,49026,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...",The Dark Knight Rises,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",Following the death of District Attorney Harve...
4,49529,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...",John Carter,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","John Carter is a war-weary, former military ca..."

In [287]:
contentdataFrame["genres"] = contentdataFrame["genres"].apply(convert)
contentdataFrame["keywords"] = contentdataFrame["keywords"].apply(convert)

In [288]:
contentdataFrame["cast"] = contentdataFrame["cast"].apply(convert3)

In [302]:
contentdataFrame["cast"].head()

0    [Sam Worthington]
1        [Johnny Depp]
2       [Daniel Craig]
3     [Christian Bale]
4      [Taylor Kitsch]
Name: cast, dtype: object

In [290]:
import ast


def Find_Director(objct):
    L = []
    # If the column was already converted or isn't a string, return it as-is
    if isinstance(objct, list):
        return objct

    if not isinstance(objct, str) or "[" not in objct:
        return L

    try:
        for i in ast.literal_eval(objct):
            if isinstance(i, dict) and i.get("job") == "Director":
                L.append(i["name"])
                break
    except (ValueError, SyntaxError):
        pass

    return L


# CRITICAL CHANGE: Save to a NEW column named "director" so "crew" stays untouched
contentdataFrame["director"] = contentdataFrame["crew"].apply(Find_Director)

# View your results
print(contentdataFrame[["crew", "director"]].head())

                                                crew             director
0  [{"credit_id": "52fe48009251416c750aca23", "de...      [James Cameron]
1  [{"credit_id": "52fe4232c3a36847f800b579", "de...     [Gore Verbinski]
2  [{"credit_id": "54805967c3a36829b5002c41", "de...         [Sam Mendes]
3  [{"credit_id": "52fe4781c3a36847f81398c3", "de...  [Christopher Nolan]
4  [{"credit_id": "52fe479ac3a36847f813eaa3", "de...     [Andrew Stanton]

In [299]:
contentdataFrame["genres"].head()

0       [Action]
1    [Adventure]
2       [Action]
3       [Action]
4       [Action]
Name: genres, dtype: object

In [ ]:
contentdataFrame["overview"] = contentdataFrame["overview"].apply(lambda x: x.split())

In [295]:
contentdataFrame["overview"]

0       [In, the, 22nd, century,, a, paraplegic, Marin...
1       [Captain, Barbossa,, long, believed, to, be, d...
2       [A, cryptic, message, from, Bond’s, past, send...
3       [Following, the, death, of, District, Attorney...
4       [John, Carter, is, a, war-weary,, former, mili...
                              ...
4804    [El, Mariachi, just, wants, to, play, his, gui...
4805    [A, newlywed, couple's, honeymoon, is, upended...
4806    ["Signed,, Sealed,, Delivered", introduces, a,...
4807    [When, ambitious, New, York, attorney, Sam, is...
4808    [Ever, since, the, second, grade, when, he, fi...
Name: overview, Length: 4806, dtype: object

## Remove space in geners
our model read the names as firs name match with the string then it will show that data is not clean well so need to clear this 
Remove the spaces

In [ ]:
# for crew
contentdataFrame["director"] = contentdataFrame["director"].apply(
    lambda x: [i.replace(" ", "") for i in x]
)
contentdataFrame["cast"] = contentdataFrame["cast"].apply(
    lambda x: [i.replace(" ", "") for i in x]
)
contentdataFrame["generes"] = contentdataFrame["title"].apply(
    lambda x: [i.replace(" ", "") for i in x]
)
contentdataFrame["keywords"] = contentdataFrame["keywords"].apply(
    lambda x: [i.replace(" ", "") for i in x]
)
# overview

TypeError: 'NoneType' object is not iterable